import type { ComponentType } from 'react';
import { BookOpen, Brain, Home, Orbit, Radio, ScrollText, Sparkles, Users, Waypoints } from 'lucide-react';
export type View = 'command'|'cosmology'|'federation'|'biology'|'characters'|'plotlines'|'chapters'|'lexicon'|'signals'|'pitches';
const nav: { id: View; label: string; cn: string; icon: ComponentType<{className?: string}> }[] = [
  { id: 'command', label: 'Command Deck', cn: '总控台', icon: Home }, { id: 'cosmology', label: 'Cosmology', cn: '世界观总纲', icon: Orbit }, { id: 'federation', label: 'Ourotopia', cn: '乌洛托比亚联邦', icon: Sparkles }, { id: 'biology', label: 'Biology & Core', cn: '生物学与核心', icon: Brain }, { id: 'characters', label: 'Characters', cn: '人物档案', icon: Users }, { id: 'plotlines', label: 'Plotlines', cn: '剧情线', icon: Waypoints }, { id: 'chapters', label: 'Chapters', cn: '章节规划', icon: BookOpen }, { id: 'lexicon', label: 'Lexicon', cn: '术语表', icon: ScrollText }, { id: 'signals', label: 'Signals', cn: '伏笔与异常', icon: Radio }, { id: 'pitches', label: 'Pitches', cn: '对外材料', icon: ScrollText },
];
export function SidebarNavigation({ active, onChange, open, onClose }: { active: View; onChange: (view: View) => void; open: boolean; onClose: () => void }) {
  return <nav className={`${open ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-50 w-72 border-r border-white/10 bg-[#050714]/95 p-5 backdrop-blur-2xl transition lg:sticky lg:top-0 lg:h-screen lg:translate-x-0`}><button onClick={onClose} className="mb-5 rounded-full border border-white/10 px-3 py-1 text-sm text-slate-300 lg:hidden">Close</button><div className="mb-8"><p className="text-xs uppercase tracking-[0.38em] text-stardust">Archive Access</p><h1 className="mt-3 text-xl font-semibold text-white">边镜宇宙档案馆</h1></div><div className="space-y-2">{nav.map(({ id, label, cn, icon: Icon }) => <button key={id} onClick={() => { onChange(id); onClose(); }} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left transition ${active === id ? 'bg-cyan-100/10 text-white shadow-[inset_0_0_0_1px_rgba(165,220,230,.25)]' : 'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon className="h-4 w-4" /><span><span className="block text-sm">{label}</span><span className="text-xs text-slate-500">{cn}</span></span></button>)}</div></nav>;
}
